all:
	clang -DNDEBUG -O0 -std=gnu++2a -stdlib=libc++ -fcxx-exceptions -pedantic -pthread -Wno-all -I$INCLUDE -pthread -I/usr/include -lstdc++ -lstdc++fs main.C -o main.o
	1;
	#clang++ -O0 -std=gnu++17 -stdlib=libc++ -Wno-all -I${INCLUDE} -pthread -lstdc++ -lstdc++fs main.C -o main.o


